

server:
  port: 8085
  servlet:
    context-path: /api
    session:
      cookie:
        domain:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  swagger2:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 192.168.145.129
    database: 1
  session:
    timeout: 86400
    store-type: redis
knife4j:
  enable: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    org.mybatis: DEBUG

